version: "3.1"
services:
  db:
    container_name: postgres15_penjualan_produk
    image: postgres:15
    restart: always
    environment:
      # - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
    volumes:
      - ./src:/code
    ports:
      - "5436:5432"
